# Traefik Configuration for Production Deployment

# API and Dashboard
api:
  dashboard: true
  insecure: false

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "app-network"
    watch: true

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@domain.com  # Replace with your email
      storage: /acme.json
      keyType: EC256
      httpChallenge:
        entryPoint: web
      # Alternative: DNS Challenge (uncomment if using DNS provider)
      # dnsChallenge:
      #   provider: cloudflare
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# Global Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Logging
log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# Metrics (optional - for monitoring)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# Pilot (optional - for monitoring)
# pilot:
#   token: "your-pilot-token"

# Tracing (optional)
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:14268/api/sampling
#     localAgentHostPort: jaeger:6831

# Rate Limiting (global)
# http:
#   middlewares:
#     default-ratelimit:
#       rateLimit:
#         burst: 100
#         average: 50
