apiVersion: v1
kind: Secret
metadata:
  name: video-streaming-secrets
  namespace: video-streaming
type: Opaque
stringData:
  # These will be populated by the deployment script
  DATABASE_URL: "PLACEHOLDER_DATABASE_URL"
  REDIS_URL: "PLACEHOLDER_REDIS_URL"
  JWT_SECRET: "PLACEHOLDER_JWT_SECRET"
  S3_BUCKET: "PLACEHOLDER_S3_BUCKET"
  AWS_REGION: "PLACEHOLDER_AWS_REGION"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: video-streaming-config
  namespace: video-streaming
data:
  RUST_LOG: "info"
  CORS_ALLOWED_ORIGINS: "PLACEHOLDER_DOMAIN,http://localhost:3000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "PLACEHOLDER_API_URL"
