apiVersion: v1
kind: Secret
metadata:
  name: video-streaming-secrets
  namespace: video-streaming
type: Opaque
stringData:
  # These will be populated by the deployment script
  DATABASE_URL: "postgres://postgres:temp_password_b947e66b32d705cf@prod-video-streaming-db.czflrq92ar26.us-west-2.rds.amazonaws.com:5432/video_streaming_db"
  REDIS_URL: "rediss://master.prod-video-streaming-redis.4e0lao.usw2.cache.amazonaws.com:6379"
  JWT_SECRET: "+nLg7xx7CeGCA0N8NaPhlI3aog4fFdphC95uG+yehrM="
  S3_BUCKET: "prod-video-streaming-videos-26ad70e7"
  AWS_REGION: "us-west-2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: video-streaming-config
  namespace: video-streaming
data:
  RUST_LOG: "info"
  CORS_ALLOWED_ORIGINS: "https://stream.harrisonng.dev,http://localhost:3000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "https://stream.harrisonng.dev/api"
