apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
  namespace: video-streaming
  labels:
    app: video-streaming-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: video-streaming-app
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-backend
  namespace: video-streaming
  labels:
    app: video-streaming-app
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: websocket
  selector:
    app: video-streaming-app
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-frontend
  namespace: video-streaming
  labels:
    app: video-streaming-app
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: frontend
  selector:
    app: video-streaming-app
