apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-streaming-sa
  namespace: video-streaming
  labels:
    app: video-streaming-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::339131303757:role/prod-video-streaming-eks-node-group-role"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: video-streaming-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: video-streaming-rolebinding
subjects:
- kind: ServiceAccount
  name: video-streaming-sa
  namespace: video-streaming
roleRef:
  kind: ClusterRole
  name: video-streaming-role
  apiGroup: rbac.authorization.k8s.io
